name: google_maps_place_picker
description: A Flutter plugin which provides 'Picking Place' using Google Maps widget.
version: 2.0.0-nullsafety.3
homepage: https://github.com/fysoul17/google_maps_place_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.0.1
  geolocator: ^9.0.0
  permission_handler: ^6.0.1+1
  provider: ^5.0.0
  google_maps_webservice:
    git:
      url: "https://github.com/Thornsopanha/google_maps_webservice.git"
      ref: master
  google_api_headers: ^1.2.0
  tuple: ^2.0.0-nullsafety.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


